# Generated by Django 4.2.3 on 2023-07-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('TC', 'TECNOLOGIA'), ('SP', 'SPORT'), ('SL', 'SALUTE'), ('TL', 'TEMPO LIBERO')], default='TL', max_length=2),
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
